version: '3'

services:
  cuisine-connect:
    stdin_open: true
    tty: true
    container_name: cuisine-connect
    build:
      context: .
      dockerfile: dev.Dockerfile

    env_file:
      - ./cuisine-connect/.env.local
    volumes:
      - ./cuisine-connect:/app
#      - ./cuisine-connect/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)
  cuisine-connect-db:
    container_name: cuisine-connect-db
    build:
      context: .
      dockerfile: mongodb.dev.Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: cuisine-connect-db
      MONGO_REPLICA_PORT: "27017"
    ports:
      - 27017:27017
    networks:
      - my_network

  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=8180
    networks:
      - my_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true